version: "3"

services:
  next-app:
    container_name: cats-boot-admin-next-app
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
    restart: unless-stopped
    ports:
      - 3003:3000
    # networks:
    #   - my_network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=catsdemo
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   my_network:
#     external: true